apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: tweet-graph
  labels:
    app.kubernetes.io/name: neo4j
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/tweetgraph123"
  NEO4J_PASSWORD: "tweetgraph123"
