apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: tweet-graph
  labels:
    app.kubernetes.io/name: neo4j
spec:
  type: ClusterIP
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app.kubernetes.io/name: neo4j
