apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tweet-graph

resources:
  - namespace.yaml
  - neo4j/deployment.yaml
  - neo4j/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - portal/deployment.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: tweet-graph
  app.kubernetes.io/managed-by: kustomize
